UNIT LanguagP;
(* Parser generated by Coco/R (Pascal version) *)

INTERFACE

PROCEDURE Parse;

FUNCTION Successful : BOOLEAN;
(* Returns TRUE if no errors have been recorded while parsing *)

PROCEDURE SynError (errNo: INTEGER);
(* Report syntax error with specified errNo *)

PROCEDURE SemError (errNo: INTEGER);
(* Report semantic error with specified errNo *)

PROCEDURE LexString (VAR Lex : STRING);
(* Retrieves Lex as exact spelling of current token *)

PROCEDURE LexName (VAR Lex : STRING);
(* Retrieves Lex as name of current token (capitalized if IGNORE CASE) *)

PROCEDURE LookAheadString (VAR Lex : STRING);
(* Retrieves Lex as exact spelling of lookahead token *)

PROCEDURE LookAheadName (VAR Lex : STRING);
(* Retrieves Lex as name of lookahead token (capitalized if IGNORE CASE) *)

IMPLEMENTATION

USES LanguagS;




CONST
  maxT = 15;
  minErrDist  =  2;  (* minimal distance (good tokens) between two errors *)
  setsize     = 16;  (* sets are stored in 16 bits *)

TYPE
  BITSET = SET OF 0 .. 15;
  SymbolSet = ARRAY [0 .. maxT DIV setsize] OF BITSET;

VAR
  symSet:  ARRAY [0 ..   0] OF SymbolSet; (*symSet[0] = allSyncSyms*)
  errDist: INTEGER;   (* number of symbols recognized since last error *)
  sym:     INTEGER;   (* current input symbol *)

PROCEDURE  SemError (errNo: INTEGER);
  BEGIN
    IF errDist >= minErrDist THEN BEGIN
      LanguagS.Error(errNo, LanguagS.line, LanguagS.col, LanguagS.pos);
    END;
    errDist := 0;
  END;

PROCEDURE  SynError (errNo: INTEGER);
  BEGIN
    IF errDist >= minErrDist THEN BEGIN
      LanguagS.Error(errNo, LanguagS.nextLine, LanguagS.nextCol, LanguagS.nextPos);
    END;
    errDist := 0;
  END;

PROCEDURE  Get;
  VAR
    s: STRING;
  BEGIN
    REPEAT
      LanguagS.Get(sym);
      IF sym <= maxT THEN
        INC(errDist)
      ELSE BEGIN
        
      END;
    UNTIL sym <= maxT
  END;

FUNCTION  _In (VAR s: SymbolSet; x: INTEGER): BOOLEAN;
  BEGIN
    _In := x MOD setsize IN s[x DIV setsize];
  END;

PROCEDURE  Expect (n: INTEGER);
  BEGIN
    IF sym = n THEN Get ELSE SynError(n);
  END;

PROCEDURE  ExpectWeak (n, follow: INTEGER);
  BEGIN
    IF sym = n
    THEN Get
    ELSE BEGIN
      SynError(n); WHILE NOT _In(symSet[follow], sym) DO Get;
    END
  END;

FUNCTION  WeakSeparator (n, syFol, repFol: INTEGER): BOOLEAN;
  VAR
    s: SymbolSet;
    i: INTEGER;
  BEGIN
    IF sym = n
    THEN BEGIN Get; WeakSeparator := TRUE; EXIT; END
    ELSE IF _In(symSet[repFol], sym) THEN BEGIN WeakSeparator := FALSE; exit END
    ELSE BEGIN
      i := 0;
      WHILE i <= maxT DIV setsize DO BEGIN
        s[i] := symSet[0, i] + symSet[syFol, i] + symSet[repFol, i]; INC(i)
      END;
      SynError(n); WHILE NOT _In(s, sym) DO Get;
      WeakSeparator := _In(symSet[syFol], sym)
    END
  END;

PROCEDURE LexName (VAR Lex : STRING);
  BEGIN
    LanguagS.GetName(LanguagS.pos, LanguagS.len, Lex)
  END;

PROCEDURE LexString (VAR Lex : STRING);
  BEGIN
    LanguagS.GetString(LanguagS.pos, LanguagS.len, Lex)
  END;

PROCEDURE LookAheadName (VAR Lex : STRING);
  BEGIN
    LanguagS.GetName(LanguagS.nextPos, LanguagS.nextLen, Lex)
  END;

PROCEDURE LookAheadString (VAR Lex : STRING);
  BEGIN
    LanguagS.GetString(LanguagS.nextPos, LanguagS.nextLen, Lex)
  END;

FUNCTION Successful : BOOLEAN;
  BEGIN
    Successful := LanguagS.errors = 0
  END;

PROCEDURE _factor; FORWARD;
PROCEDURE _term; FORWARD;
PROCEDURE _intname; FORWARD;
PROCEDURE _end; FORWARD;
PROCEDURE _expression; FORWARD;
PROCEDURE _bgn; FORWARD;
PROCEDURE _def; FORWARD;
PROCEDURE _var; FORWARD;
PROCEDURE _name; FORWARD;
PROCEDURE _prg; FORWARD;
PROCEDURE _Language; FORWARD;

PROCEDURE _factor;
  BEGIN
    IF (sym = 2) THEN BEGIN
      Get;
    END ELSE IF (sym = 1) THEN BEGIN
      Get;
    END ELSE BEGIN SynError(16);
    END;
  END;

PROCEDURE _term;
  BEGIN
    _factor;
    WHILE (sym = 12) OR (sym = 13) DO BEGIN
      IF (sym = 12) THEN BEGIN
        Get;
        _factor;
      END ELSE BEGIN
        Get;
        _factor;
      END;
    END;
  END;

PROCEDURE _intname;
  BEGIN
    Expect(8);
  END;

PROCEDURE _end;
  BEGIN
    Expect(14);
  END;

PROCEDURE _expression;
  BEGIN
    _term;
    WHILE (sym = 10) OR (sym = 11) DO BEGIN
      IF (sym = 10) THEN BEGIN
        Get;
        _term;
      END ELSE BEGIN
        Get;
        _term;
      END;
    END;
  END;

PROCEDURE _bgn;
  BEGIN
    Expect(9);
  END;

PROCEDURE _def;
  BEGIN
    Expect(1);
    Expect(7);
    _intname;
    Expect(3);
  END;

PROCEDURE _var;
  BEGIN
    Expect(6);
  END;

PROCEDURE _name;
  BEGIN
    Expect(1);
  END;

PROCEDURE _prg;
  BEGIN
    Expect(5);
  END;

PROCEDURE _Language;
  BEGIN
    _prg;
    _name;
    Expect(3);
    IF (sym = 6) THEN BEGIN
      _var;
      WHILE (sym = 1) DO BEGIN
        _def;
      END;
    END;
    _bgn;
    WHILE (sym = 1) OR (sym = 2) DO BEGIN
      _expression;
    END;
    _end;
    _name;
    Expect(4);
  END;



PROCEDURE  Parse;
  BEGIN
    _Reset; Get;
    _Language;

  END;

BEGIN
  errDist := minErrDist;
  symSet[ 0, 0] := [0];
END. (* LanguagP *)
