UNIT LanguagS;
(* Scanner generated by Coco/R (Pascal version) *)

INTERFACE

CONST
  CommentMax = 10000;
TYPE
  CommentStr = ARRAY [0 .. CommentMax] OF CHAR;
VAR
  src:         FILE;         (*source/list files. To be opened by the main pgm*)
  lst:         TEXT;
  directory:   STRING;       (*of source file*)
  line, col:   INTEGER;      (*line and column of current symbol*)
  len:         LONGINT;      (*length of current symbol*)
  pos:         LONGINT;      (*file position of current symbol*)
  nextLine:    INTEGER;      (*line of lookahead symbol*)
  nextCol:     INTEGER;      (*column of lookahead symbol*)
  nextLen:     LONGINT;      (*length of lookahead symbol*)
  nextPos:     LONGINT;      (*file position of lookahead symbol*)
  errors:      INTEGER;      (*number of detected errors*)
  seenComment: BOOLEAN;      (*TRUE if comments have been registered*)
  Error:       PROCEDURE (nr, line, col: INTEGER; pos: LONGINT);

PROCEDURE Get (VAR sym: INTEGER);
(* Gets next symbol from source file *)

PROCEDURE GetString (pos: LONGINT; len: INTEGER; VAR s: STRING);
(* Retrieves exact string of max length len from position pos in source file *)

PROCEDURE GetName (pos: LONGINT; len: INTEGER; VAR s: STRING);
(* Retrieves name of symbol of length len at position pos in source file *)

FUNCTION CharAt (pos: LONGINT): CHAR;
(* Returns exact character at position pos in source file *)

PROCEDURE GetComment (VAR comment: CommentStr; pos: INTEGER; VAR length: INTEGER);
(* IF seenComment
     THEN concatenates and extracts previously scanned comments into comment,
          starting at comment[pos], and computes length; seenComment := FALSE
     ELSE returns length := 0 *)

PROCEDURE _Reset;
(* Reads and stores source file internally *)

IMPLEMENTATION

CONST
  no_Sym = 15; (*error token code*)
  (* not only for errors but also for not finished states of scanner analysis *)
  eof = #26; (*MS-DOS eof*)
  LF  = #10;
  CR  = #13;
  EF  = #0;
  EL  = CR;
  BlkSize = 16384;
TYPE
  BufBlock   = ARRAY [0 .. BlkSize-1] OF CHAR;
  Buffer     = ARRAY [0 .. 31] OF ^BufBlock;
  StartTable = ARRAY [0 .. 255] OF INTEGER;
  GetCH      = FUNCTION (pos: LONGINT) : CHAR;
  CommentPtr = ^ CommentRec;
  CommentRec = RECORD
                 begCom, endCom : LONGINT;
                 next : CommentPtr;
               END;
VAR
  lastCh,
  ch:        CHAR;       (*current input character*)
  curLine:   INTEGER;    (*current input line (may be higher than line)*)
  lineStart: LONGINT;    (*start position of current line*)
  apx:       LONGINT;    (*length of appendix (CONTEXT phrase)*)
  oldEols:   INTEGER;    (*number of _EOLs in a comment*)
  bp, bp0:   LONGINT;    (*current position in buf
                           (bp0: position of current token)*)
  LBlkSize:  LONGINT;    (*BlkSize*)
  inputLen:  LONGINT;    (*source file size*)
  buf:       Buffer;     (*source buffer for low-level access*)
  start:     StartTable; (*start state for every character*)
  CurrentCh: GetCH;
  firstComment, lastComment: CommentPtr;

PROCEDURE Err (nr, line, col: INTEGER; pos: LONGINT); FAR;
  BEGIN
    INC(errors)
  END;

PROCEDURE NextCh;
(* Return global variable ch *)
  BEGIN
    lastCh := ch; INC(bp); ch := CurrentCh(bp);
    IF (ch = EL) OR (ch = LF) AND (lastCh <> EL) THEN BEGIN
      INC(curLine); lineStart := bp
    END
  END;

FUNCTION Comment: BOOLEAN;
  LABEL
    999;
  VAR
    level, startLine: INTEGER;
    oldLineStart : LONGINT;
    beginC, endC : LONGINT;
    nextComment : CommentPtr;
  BEGIN
    beginC := bp;
    level := 1; startLine := curLine; oldLineStart := lineStart;
    
    Comment := FALSE;
    999:
    endC := bp; DEC(endC);
    IF endC > beginC THEN BEGIN
      seenComment := TRUE;
      NEW(nextComment);
      nextComment^.begCom := beginC;
      nextComment^.endCom := endC;
      nextComment^.next := NIL;
      IF firstComment = NIL
        THEN firstComment := nextComment
        ELSE lastComment^.next := nextComment;
      lastComment := nextComment
    END
  END;

PROCEDURE GetComment (VAR comment: CommentStr; pos: INTEGER; VAR length: INTEGER);
  VAR
    this : CommentPtr;
  BEGIN
    length := 0;
    WHILE firstComment <> NIL DO BEGIN
      this := firstComment;
      WHILE (pos + length <= CommentMax) AND (this^.begCom <= this^.endCom) DO
        BEGIN
          comment[pos + length] := CharAt(this^.begCom);
          INC(length); INC(this^.begCom);
        END;
      firstComment := firstComment^.next;
      DISPOSE(this)
    END;
    seenComment := FALSE;
  END;

PROCEDURE Get (VAR sym: INTEGER);
  VAR
    state: INTEGER;

  FUNCTION Equal (s: STRING): BOOLEAN;
    VAR
      i: INTEGER;
      q: LONGINT;
    BEGIN
      IF nextLen <> Length(s) THEN BEGIN Equal := FALSE; EXIT END;
      i := 1; q := bp0;
      WHILE i <= nextLen DO BEGIN
        IF CurrentCh(q) <> s[i] THEN BEGIN Equal := FALSE; EXIT END;
        INC(i); INC(q)
      END;
      Equal := TRUE
    END;

  PROCEDURE CheckLiteral;
    BEGIN
      CASE CurrentCh(bp0) OF
        'B': IF Equal('BEGIN') THEN BEGIN sym := 9; 
             END;
        'E': IF Equal('END') THEN BEGIN sym := 14; 
             END;
        'I': IF Equal('INTEGER') THEN BEGIN sym := 8; 
             END;
        'P': IF Equal('PROGRAM') THEN BEGIN sym := 5; 
             END;
        'V': IF Equal('VAR') THEN BEGIN sym := 6; 
             END;
      ELSE BEGIN END
      END
    END;

  BEGIN (*Get*)
    WHILE (ch = ' ') OR
          ((ch >= CHR(9)) AND (ch <= CHR(10)) OR
          (ch = CHR(13))) DO NextCh;
    pos := nextPos;   nextPos := bp;
    col := nextCol;   nextCol := bp - lineStart;
    line := nextLine; nextLine := curLine;
    len := nextLen;   nextLen := 0;
    apx := 0; state := start[ORD(ch)]; bp0 := bp;
    WHILE TRUE DO BEGIN
      NextCh; INC(nextLen);
      CASE state OF
         1: IF ((ch >= '0') AND (ch <= '9') OR
               (ch >= 'A') AND (ch <= 'Z') OR
               (ch >= 'a') AND (ch <= 'z')) THEN BEGIN 
            END ELSE BEGIN sym := 1; CheckLiteral; EXIT; END;
         2: IF ((ch >= '0') AND (ch <= '9')) THEN BEGIN 
            END ELSE BEGIN sym := 2; EXIT; END;
         3: BEGIN sym := 3; EXIT; END;
         4: BEGIN sym := 4; EXIT; END;
         5: BEGIN sym := 7; EXIT; END;
         6: BEGIN sym := 10; EXIT; END;
         7: BEGIN sym := 11; EXIT; END;
         8: BEGIN sym := 12; EXIT; END;
         9: BEGIN sym := 13; EXIT; END;
        10: BEGIN sym := 0; ch := #0; DEC(bp); EXIT END;
      ELSE BEGIN sym := no_Sym; EXIT (*NextCh already done*) END;
      END
    END
  END;

PROCEDURE GetString (pos: LONGINT; len: INTEGER; VAR s: STRING);
  VAR
    i: INTEGER;
    p: LONGINT;
  BEGIN
    IF len > 255 THEN len := 255;
    p := pos; i := 1;
    WHILE i <= len DO BEGIN
      s[i] := CharAt(p); INC(i); INC(p)
    END;
    s[0] := CHR(len);
  END;

PROCEDURE GetName (pos: LONGINT; len: INTEGER; VAR s: STRING);
  VAR
    i: INTEGER;
    p: LONGINT;
  BEGIN
    IF len > 255 THEN len := 255;
    p := pos; i := 1;
    WHILE i <= len DO BEGIN
      s[i] := CurrentCh(p); INC(i); INC(p)
    END;
    s[0] := CHR(len);
  END;

FUNCTION CharAt (pos: LONGINT): CHAR;
  VAR
    ch : CHAR;
  BEGIN
    IF pos >= inputLen THEN BEGIN CharAt := EF; EXIT; END;
    ch := buf[pos DIV LBlkSize]^[pos MOD LBlkSize];
    IF ch <> eof THEN CharAt := ch ELSE CharAt := EF
  END;

FUNCTION CapChAt (pos: LONGINT): CHAR; FAR;
  VAR
    ch : CHAR;
  BEGIN
    IF pos >= inputLen THEN BEGIN CapChAt := EF; EXIT; END;
    ch := upcase(buf[pos DIV LBlkSize]^[pos MOD LBlkSize]);
    IF ch <> eof THEN CapChAt := ch ELSE CapChAt := EF
  END;

PROCEDURE _Reset;
  VAR
    len: LONGINT;
    i, read: INTEGER;
  BEGIN (*assert: src has been opened*)
    len := FileSize(src); i := 0; inputLen := len;
    WHILE len > LBlkSize DO BEGIN
      NEW(buf[i]);
      read := BlkSize; BlockRead(src, buf[i]^, read);
      len := len - read; INC(i)
    END;
    NEW(buf[i]);
    read := len; BlockRead(src, buf[i]^, read);
    buf[i]^[read] := EF;
    curLine := 1; lineStart := -2; bp := -1;
    oldEols := 0; apx := 0; errors := 0;
    NextCh;
  END;

BEGIN
  CurrentCh := CharAt;
  start[  0] := 10; start[  1] := 11; start[  2] := 11; start[  3] := 11; 
  start[  4] := 11; start[  5] := 11; start[  6] := 11; start[  7] := 11; 
  start[  8] := 11; start[  9] := 11; start[ 10] := 11; start[ 11] := 11; 
  start[ 12] := 11; start[ 13] := 11; start[ 14] := 11; start[ 15] := 11; 
  start[ 16] := 11; start[ 17] := 11; start[ 18] := 11; start[ 19] := 11; 
  start[ 20] := 11; start[ 21] := 11; start[ 22] := 11; start[ 23] := 11; 
  start[ 24] := 11; start[ 25] := 11; start[ 26] := 11; start[ 27] := 11; 
  start[ 28] := 11; start[ 29] := 11; start[ 30] := 11; start[ 31] := 11; 
  start[ 32] := 11; start[ 33] := 11; start[ 34] := 11; start[ 35] := 11; 
  start[ 36] := 11; start[ 37] := 11; start[ 38] := 11; start[ 39] := 11; 
  start[ 40] := 11; start[ 41] := 11; start[ 42] :=  8; start[ 43] :=  6; 
  start[ 44] := 11; start[ 45] :=  7; start[ 46] :=  4; start[ 47] :=  9; 
  start[ 48] :=  2; start[ 49] :=  2; start[ 50] :=  2; start[ 51] :=  2; 
  start[ 52] :=  2; start[ 53] :=  2; start[ 54] :=  2; start[ 55] :=  2; 
  start[ 56] :=  2; start[ 57] :=  2; start[ 58] :=  5; start[ 59] :=  3; 
  start[ 60] := 11; start[ 61] := 11; start[ 62] := 11; start[ 63] := 11; 
  start[ 64] := 11; start[ 65] :=  1; start[ 66] :=  1; start[ 67] :=  1; 
  start[ 68] :=  1; start[ 69] :=  1; start[ 70] :=  1; start[ 71] :=  1; 
  start[ 72] :=  1; start[ 73] :=  1; start[ 74] :=  1; start[ 75] :=  1; 
  start[ 76] :=  1; start[ 77] :=  1; start[ 78] :=  1; start[ 79] :=  1; 
  start[ 80] :=  1; start[ 81] :=  1; start[ 82] :=  1; start[ 83] :=  1; 
  start[ 84] :=  1; start[ 85] :=  1; start[ 86] :=  1; start[ 87] :=  1; 
  start[ 88] :=  1; start[ 89] :=  1; start[ 90] :=  1; start[ 91] := 11; 
  start[ 92] := 11; start[ 93] := 11; start[ 94] := 11; start[ 95] := 11; 
  start[ 96] := 11; start[ 97] :=  1; start[ 98] :=  1; start[ 99] :=  1; 
  start[100] :=  1; start[101] :=  1; start[102] :=  1; start[103] :=  1; 
  start[104] :=  1; start[105] :=  1; start[106] :=  1; start[107] :=  1; 
  start[108] :=  1; start[109] :=  1; start[110] :=  1; start[111] :=  1; 
  start[112] :=  1; start[113] :=  1; start[114] :=  1; start[115] :=  1; 
  start[116] :=  1; start[117] :=  1; start[118] :=  1; start[119] :=  1; 
  start[120] :=  1; start[121] :=  1; start[122] :=  1; start[123] := 11; 
  start[124] := 11; start[125] := 11; start[126] := 11; start[127] := 11; 
  start[128] := 11; start[129] := 11; start[130] := 11; start[131] := 11; 
  start[132] := 11; start[133] := 11; start[134] := 11; start[135] := 11; 
  start[136] := 11; start[137] := 11; start[138] := 11; start[139] := 11; 
  start[140] := 11; start[141] := 11; start[142] := 11; start[143] := 11; 
  start[144] := 11; start[145] := 11; start[146] := 11; start[147] := 11; 
  start[148] := 11; start[149] := 11; start[150] := 11; start[151] := 11; 
  start[152] := 11; start[153] := 11; start[154] := 11; start[155] := 11; 
  start[156] := 11; start[157] := 11; start[158] := 11; start[159] := 11; 
  start[160] := 11; start[161] := 11; start[162] := 11; start[163] := 11; 
  start[164] := 11; start[165] := 11; start[166] := 11; start[167] := 11; 
  start[168] := 11; start[169] := 11; start[170] := 11; start[171] := 11; 
  start[172] := 11; start[173] := 11; start[174] := 11; start[175] := 11; 
  start[176] := 11; start[177] := 11; start[178] := 11; start[179] := 11; 
  start[180] := 11; start[181] := 11; start[182] := 11; start[183] := 11; 
  start[184] := 11; start[185] := 11; start[186] := 11; start[187] := 11; 
  start[188] := 11; start[189] := 11; start[190] := 11; start[191] := 11; 
  start[192] := 11; start[193] := 11; start[194] := 11; start[195] := 11; 
  start[196] := 11; start[197] := 11; start[198] := 11; start[199] := 11; 
  start[200] := 11; start[201] := 11; start[202] := 11; start[203] := 11; 
  start[204] := 11; start[205] := 11; start[206] := 11; start[207] := 11; 
  start[208] := 11; start[209] := 11; start[210] := 11; start[211] := 11; 
  start[212] := 11; start[213] := 11; start[214] := 11; start[215] := 11; 
  start[216] := 11; start[217] := 11; start[218] := 11; start[219] := 11; 
  start[220] := 11; start[221] := 11; start[222] := 11; start[223] := 11; 
  start[224] := 11; start[225] := 11; start[226] := 11; start[227] := 11; 
  start[228] := 11; start[229] := 11; start[230] := 11; start[231] := 11; 
  start[232] := 11; start[233] := 11; start[234] := 11; start[235] := 11; 
  start[236] := 11; start[237] := 11; start[238] := 11; start[239] := 11; 
  start[240] := 11; start[241] := 11; start[242] := 11; start[243] := 11; 
  start[244] := 11; start[245] := 11; start[246] := 11; start[247] := 11; 
  start[248] := 11; start[249] := 11; start[250] := 11; start[251] := 11; 
  start[252] := 11; start[253] := 11; start[254] := 11; start[255] := 11; 
  Error := Err; LBlkSize := BlkSize; lastCh := EF;
  firstComment := NIL; seenComment := FALSE;
END. (* LanguagS *)
